# Generated by Django 4.2.19 on 2025-02-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=200)),
                ('location', models.CharField(blank=True, null=True)),
                ('occupation', models.CharField(choices=[('IL', 'Illustrator'), ('IN', 'Influencer'), ('ST', 'Stylist'), ('SD', 'Set Designer')])),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
