# Generated by Django 4.2.19 on 2025-02-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
