# Generated by Django 4.2.19 on 2025-03-01 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_alter_talent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='talent_profiles/'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='occupation',
            field=models.CharField(choices=[('IL', 'Illustrator'), ('IN', 'Influencer'), ('ST', 'Stylist'), ('SD', 'Set Designer')], max_length=2),
        ),
        migrations.CreateModel(
            name='TalentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='talent_gallery/')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='talent.talent')),
            ],
        ),
    ]
